### ISSUE TITLE
What song is used by PSK and ROT?

### ISSUE THREAD

**Issue by kittybwained** [skadakar/garble#1]
Hello, i was just wondering which song PSK and ROT used? I know OTP's but not sure about these two.

**Comment by skadakar** [comment]
PSK: [Trash Compactor Waltz](https://www.youtube.com/watch?v=DCrZ6kuAZFM)
ROT: apparently none.. make a PR with something if you want :)

**Comment by kittybwained** [comment]
> PSK: [Trash Compactor Waltz](https://www.youtube.com/watch?v=DCrZ6kuAZFM) ROT: apparently none.. make a PR with something if you want :)

Thanks! Canon in D could work, might do that
Also, which one is VIG? I actually meant to say VIG but must have typed ROT because of the other issue
